theme: jekyll-theme-minimal
title: PhD. Lê Toàn Thắng - Trang tin chính
description: Business Analytics - Data Analytics vs Data Scientist and Develop CI/CD Pipeline Data Framework with copilot-kit (AI/ML/DL)
